"""initial procurement schema

Revision ID: b088bb588596
Revises: 
Create Date: 2026-10-05 06:00:56.475630

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'b088bb588596'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_name'), ['name'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('auth_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_sessions_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_auth_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('organization_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'user_id', name='uq_organization_memberships_org_user')
    )
    with op.batch_alter_table('organization_memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_memberships_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_memberships_user_id'), ['user_id'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_organization_id'), ['organization_id'], unique=False)

    op.create_table('procurement_packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('mode', sa.String(length=30), nullable=False),
    sa.Column('technical_bid_locked', sa.Boolean(), nullable=False),
    sa.Column('commercial_evaluation_open', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('procurement_packages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_procurement_packages_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_procurement_packages_project_id'), ['project_id'], unique=False)

    op.create_table('requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=100), nullable=False),
    sa.Column('parameter', sa.String(length=200), nullable=False),
    sa.Column('required_value', sa.String(length=250), nullable=False),
    sa.Column('requirement_type', sa.String(length=30), nullable=False),
    sa.Column('acceptance_rule', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['procurement_packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_requirements_package_id'), ['package_id'], unique=False)

    op.create_table('vendor_offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('vendor_name', sa.String(length=200), nullable=False),
    sa.Column('vendor_key', sa.String(length=200), nullable=False),
    sa.Column('technical_revision', sa.String(length=50), nullable=False),
    sa.Column('technical_status', sa.String(length=40), nullable=False),
    sa.Column('commercial_status', sa.String(length=30), nullable=False),
    sa.Column('price', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('lead_time', sa.String(length=100), nullable=True),
    sa.Column('warranty', sa.String(length=100), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['procurement_packages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('package_id', 'vendor_key', 'technical_revision', name='uq_vendor_offers_package_vendor_revision')
    )
    with op.batch_alter_table('vendor_offers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendor_offers_package_id'), ['package_id'], unique=False)

    op.create_table('technical_clarifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['offer_id'], ['vendor_offers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('technical_clarifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_technical_clarifications_offer_id'), ['offer_id'], unique=False)

    op.create_table('technical_deviations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('parameter', sa.String(length=200), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['offer_id'], ['vendor_offers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('technical_deviations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_technical_deviations_offer_id'), ['offer_id'], unique=False)

    op.create_table('vendor_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=True),
    sa.Column('document_type', sa.String(length=30), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['vendor_offers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vendor_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendor_documents_offer_id'), ['offer_id'], unique=False)

    op.create_table('vendor_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('parameter', sa.String(length=200), nullable=False),
    sa.Column('value', sa.String(length=250), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('claim_status', sa.String(length=40), nullable=False),
    sa.Column('source_document_id', sa.Integer(), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('source_section', sa.String(length=200), nullable=True),
    sa.Column('source_table', sa.String(length=100), nullable=True),
    sa.Column('source_cell', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['offer_id'], ['vendor_offers.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['vendor_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vendor_claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendor_claims_offer_id'), ['offer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendor_claims_source_document_id'), ['source_document_id'], unique=False)

    op.create_table('vendor_document_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['vendor_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vendor_document_pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendor_document_pages_document_id'), ['document_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_document_pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendor_document_pages_document_id'))

    op.drop_table('vendor_document_pages')
    with op.batch_alter_table('vendor_claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendor_claims_source_document_id'))
        batch_op.drop_index(batch_op.f('ix_vendor_claims_offer_id'))

    op.drop_table('vendor_claims')
    with op.batch_alter_table('vendor_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendor_documents_offer_id'))

    op.drop_table('vendor_documents')
    with op.batch_alter_table('technical_deviations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_technical_deviations_offer_id'))

    op.drop_table('technical_deviations')
    with op.batch_alter_table('technical_clarifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_technical_clarifications_offer_id'))

    op.drop_table('technical_clarifications')
    with op.batch_alter_table('vendor_offers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendor_offers_package_id'))

    op.drop_table('vendor_offers')
    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requirements_package_id'))

    op.drop_table('requirements')
    with op.batch_alter_table('procurement_packages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_procurement_packages_project_id'))
        batch_op.drop_index(batch_op.f('ix_procurement_packages_category'))

    op.drop_table('procurement_packages')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_organization_id'))

    op.drop_table('projects')
    with op.batch_alter_table('organization_memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_organization_memberships_organization_id'))

    op.drop_table('organization_memberships')
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_auth_sessions_token_hash'))

    op.drop_table('auth_sessions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_name'))

    op.drop_table('organizations')
    # ### end Alembic commands ###
